[package]
name = "shutdown-helper"
version = "1.0.4"
edition = "2024"

[dependencies]
constant_time_eq = "0.3"
httparse = "1.10"
log = "0.4"
simplelog = "0.12"
dotenvy = "0.15"
windows-service = "0.7"
windows-sys = { version = "0.52", features = ["Win32_System_Shutdown", "Win32_Foundation", "Win32_Security", "Win32_System_Threading"] }

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
