[package]
name = "shutdown-helper"
version = "1.0.6"
edition = "2024"

[dependencies]
constant_time_eq = "0.3.1"
httparse = "1.10.1"
system_shutdown = "4.1.0"
log = "0.4.23"
simplelog = "0.12.2"
dotenvy = "0.15.7"
windows-service = "0.8.0"

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
